### ISSUE TITLE
software release

### ISSUE THREAD

**Issue by rogerkuou** [MotionbyLearning/sarxarray#33]
- [x] Documentation
- [x] Tests
   - [x] GitHub automated testing
- [x] Testing actions
- [x] Citations
- [x] Tutorials
- [x] Publish to PyPI
- [x] Checklist: [![OpenSSF Best Practices](https://www.bestpractices.dev/projects/7980/badge)](https://www.bestpractices.dev/projects/7980)
  - [x] Add check list
  - [x] Contributor information
  - [x] Release number mechanism

**Comment by fnattino** [comment]
Just some thoughts, on related topics in random order:
- In terms of best practices as recommended by [fair-software.nl](https://fair-software.nl), I think only the [checklist](https://fair-software.nl/recommendations/checklist) is missing. 
- For the citation of the software, in addition to adding the CITATION.cff file (you can build it [here](https://citation-file-format.github.io/cff-initializer-javascript/#/)), also add a `.zenodo.json` file (you can create it with the [cffconvert](https://github.com/citation-file-format/cffconvert)).
- Related to the Publish to PyPI, I would make sure you use a GitHub action for that, since it is so much more convenient (see e.g. [the one in CGC](https://github.com/phenology/cgc/blob/master/.github/workflows/pypi.yml)).  
- Also good to have:
  - CHANGELOG file to describe changes 
  - CODE_OF_CONDUCT and CONTRIBUTING (there are some default ones out there, you can then link them in the docs or in the main README file)
- Optional, but I think useful as some point is to move project metadata to a `pyproject.toml` (functionalities from `setup.py` are being deprecated), also see [example in CGC](https://github.com/phenology/cgc/blob/master/pyproject.toml).
